<a href="https://colab.research.google.com/github/Willi-blip/ejecicios/blob/main/Ejercicios_basicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPY, Libreria de ciencia de datos

In [41]:
import numpy as np
#pip install numpy

ARRAYS DE 1 DIMENSION

In [5]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [ ]:
array_id

ARRAYS DE 2 DIMENSIONES

In [6]:
array_2d=np.array([(10,20,30),(40,50,50)])
array_2d

array([[10, 20, 30],
       [40, 50, 50]])

ARRATS DE 3 DIMENSIONES

In [8]:
array_3d=np.array([(10,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON 0 DE 3 FILAS 4 CULUMNAS

In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ARRAY DE UNOS CON2 DIMENSIONES 4 FILAS 5 COLUMNAS

In [15]:
np.ones([2,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [18]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

ARRAYS CON INTERVALOS Y DIVISIONES

In [26]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAY CON VALORES DADOS

In [27]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY MATRIZ IDENTIDAD, DIAGONAL, DE UNOS

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS

In [35]:
np.random.random((4,4))

array([[0.22097647, 0.48595463, 0.40543539, 0.98178174],
       [0.82150092, 0.12912591, 0.20897037, 0.35526123],
       [0.49613813, 0.18105079, 0.60405846, 0.30800038],
       [0.42811414, 0.18479222, 0.55975856, 0.47935327]])

ARRAY NUMEROS VACIOS 4*3

In [45]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [50]:
#grabar
np.save('mi_array_3d',array_3d)

In [54]:
#cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [55]:
np.save('mi_array_2d',array_2d)

In [56]:
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [40, 50, 50]])

GRABAR Y CARGAR FICHEROS DE TEXTOS

In [57]:
#grabar el fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=' ')

In [58]:
#cargar el fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [40., 50., 50.]])